# general settings
# modelname: IconVSRNet RealBasicVSRNet
name: vid4_CAD2VSRnew
model_type: VideoRecurrentModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: Vimeo90K
    type: Vimeo90KRecurrentDataset
    dataroot_gt: /data1/userhome/luwen/Code/wzy/vimeo90k/GT
    # dataroot_lq: /data1/userhome/luwen/Code/wzy/REDS/train_sharp
    dataroot_lq: /data1/userhome/luwen/Code/wzy/vimeo90k/BDx4
    lq_subroot:  [BD, BD, BD, BD15, BD25, BD35]
    dataroot_meta: datasets/Vimeo/lq/meta
    meta_subroot: [0,0,0,15,25,35]
    meta_info_file: /data1/userhome/luwen/Code/wzy/CAD2VSR/basicsr/data/meta_info/meta_info_Vimeo90K_train_GT.txt
    val_partition: REDS4
    test_mode: true
    io_backend:
      type: disk

    num_frame: 20
    gt_size: 256
    interval_list: [1]
    random_reverse: false
    use_hflip: true
    use_rot: true
    flip_sequence: false # true
    # data loader
    num_worker_per_gpu: 16
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 20
    prefetch_mode: ~

  val_15:
    name: Vid4_BD15
    type: VideoRecurrentTestDataset
    dataroot_gt: /data1/userhome/luwen/Code/wzy/vid4_crf/GT
    dataroot_lq: /data1/userhome/luwen/Code/wzy/vid4_crf/BD_15
    cache_data: true
    io_backend:
      type: disk
    num_frame: -1

  val_25:
    name: Vid4_BD25
    type: VideoRecurrentTestDataset
    dataroot_gt: /data1/userhome/luwen/Code/wzy/vid4_crf/GT
    dataroot_lq: /data1/userhome/luwen/Code/wzy/vid4_crf/BD_25
    cache_data: true
    io_backend:
      type: disk
    num_frame: -1

  val_35:
    name: Vid4_BD35
    type: VideoRecurrentTestDataset
    dataroot_gt: /data1/userhome/luwen/Code/wzy/vid4_crf/GT
    dataroot_lq: /data1/userhome/luwen/Code/wzy/vid4_crf/BD_35
    cache_data: true
    io_backend:
      type: disk
    num_frame: -1

  # val_15:
  #   name: REDS4_BD15
  #   type: VideoRecurrentTestDataset
  #   dataroot_gt: /data1/userhome/luwen/Code/wzy/REDS/train_sharp
  #   dataroot_lq: /data1/userhome/luwen/Code/wzy/REDS/train_sharp_bicubic_BD15/X4
  #   cache_data: true
  #   meta_info_file: /data1/userhome/luwen/Code/wzy/CAD2VSR/basicsr/data/meta_info/meta_info_REDS4_test_GT.txt
  #   io_backend:
  #     type: disk
  #   num_frame: 20

  # val_25:
  #   name: REDS4_BD25
  #   type: VideoRecurrentTestDataset
  #   dataroot_gt: /data1/userhome/luwen/Code/wzy/REDS/train_sharp
  #   dataroot_lq: /data1/userhome/luwen/Code/wzy/REDS/train_sharp_bicubic_BD25/X4
  #   cache_data: true
  #   meta_info_file: /data1/userhome/luwen/Code/wzy/CAD2VSR/basicsr/data/meta_info/meta_info_REDS4_test_GT.txt
  #   io_backend:
  #     type: disk
  #   num_frame: 20

  # val_35:
  #   name: REDS4_BD35
  #   type: VideoRecurrentTestDataset
  #   dataroot_gt: /data1/userhome/luwen/Code/wzy/REDS/train_sharp
  #   dataroot_lq: /data1/userhome/luwen/Code/wzy/REDS/train_sharp_bicubic_BD35/X4
  #   cache_data: true
  #   meta_info_file: /data1/userhome/luwen/Code/wzy/CAD2VSR/basicsr/data/meta_info/meta_info_REDS4_test_GT.txt
  #   io_backend:
  #     type: disk
  #   num_frame: 20



# network structures
# network_g:
#   type: CAVSR
#   num_block: 25

# 纯粹的basicVSR CVPR2021，没有其他参数，直接使用
# network_g:
#   type: BasicVSRNet

# BasicVSR++
network_g:
  type: CAD2VSR
  spynet_pretrained: '/data1/userhome/luwen/Code/wzy/CAD2VSR/spynet_20210409-c6c1bd09.pth'
  mid_channels: 64
  num_propagation_blocks: 20
  num_cleaning_blocks: 20
  dynamic_refine_thres: 255 

# EDVR
# network_g:
#   type: FTVSR

# path
path:
  pretrain_network_g: /data1/userhome/luwen/Code/wzy/CAD2VSR/experiments/vid4_CAD2VSR/models/net_g_400000.pth
  # pretrain_network_g: /data1/userhome/luwen/Code/wzy/CAD2VSR/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds_20211027-0e2ff207.pth
  strict_load_g: false
  # resume_state: /data1/userhome/luwen/Code/wzy/CAD2VSR/experiments/vid4_CAD2VSR/training_states/50000.state

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [400000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 400000
  warmup_iter: -1  # no warm up
  fix_flow: 5000
  flow_lr_mul: 0.125

  # losses
  pixel_opt:
    # type: bi_SD_CharbonnierLoss
    # loss_weight: [0.5, 0.25, 0.25]
    type: CharbonnierLoss_gae
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5000
  save_img: true

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: true
    ssim: # metric name, can be arbitrary
      type: calculate_ssim
      crop_border: 0
      test_y_channel: true


# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5000
  use_tb_logger: false
  # wandb:
  #   project: vsr_best
  #   resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

find_unused_parameters: true
